### ISSUE TITLE
GCP stop

### ISSUE THREAD

**Issue by desaiak** [sequenceiq/uluwatu#171]
Seems like one the main page the stop button is greyed out but it exists as active on the detail page. I don't think the functionality to stop clusters on GCP is implemented yet?

![screen shot 2015-02-07 at 3 55 25 pm](https://cloud.githubusercontent.com/assets/1720389/6093911/e8c7f54c-aee1-11e4-879b-1f0f2e0d7e26.png)
![screen shot 2015-02-07 at 3 55 17 pm](https://cloud.githubusercontent.com/assets/1720389/6093912/e8d40e68-aee1-11e4-8e62-bb68eaf11289.png)

**Comment by doktoric** [comment]
You can stop your cluster on gcp because this functionality is supported by cloudbreak
