### ISSUE TITLE
Create blueprint - name validation

### ISSUE THREAD

**Issue by matyix** [sequenceiq/uluwatu#204]
Name validation is wrong (max length is misleading), as the actual name is shorter than indicated.

**Comment by doktoric** [comment]
I fixed this issue with in the [#203] (https://github.com/sequenceiq/uluwatu/pull/203) PR.
here is the fix https://github.com/sequenceiq/uluwatu/blob/ambari-reinstall-new/app/static/tags/blueprint/bpform.tag#L4
After the merge it will works fine.
